eka_str = input("Anna kokonaisluku: ")
toka_str = input("Anna toinen: ")
kolmas_str = input("Ja vielä yks: ")
eka: int = int(eka_str)
toka: int = int(toka_str)
kolmas: int = int(kolmas_str)
print("Lukujen summa: ", eka+toka+kolmas)
print("Lukuen tulos: ", eka*toka*kolmas)
print("Lukuen keskiarvo: ", (eka+toka+kolmas)/3)
