import random
num1 = (random.randint(0, 9))
num2 = (random.randint(0, 9))
num3 = (random.randint(0, 9))
num4 = (random.randint(1, 6))
num5 = (random.randint(1, 6))
num6 = (random.randint(1, 6))
num7 = (random.randint(1, 6))
print("Ensimmäinen numerolukon koodi on: "+str(num1)+str(num2)+str(num3))
print("Toinen numerolukonkoodi on: "+str(num4)+str(num5)+str(num6)+str(num7))